# Generated by Django 4.2.7 on 2025-09-04 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demofile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.demosession'),
        ),
    ]
