# Generated by Django 4.2.7 on 2025-09-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demosession',
            name='user',
        ),
    ]
