# Generated by Django 4.2.7 on 2025-09-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=30)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('result_data', models.JSONField()),
                ('processing_time', models.FloatField()),
                ('model_used', models.CharField(max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.demosession')),
            ],
        ),
    ]
