# Generated by Django 4.2.7 on 2025-10-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_remove_demosession_user'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='segmentation_input/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='segmentation_output/')),
                ('segments', models.JSONField(default=list)),
                ('ai_description', models.TextField(blank=True)),
                ('technical_summary', models.TextField(blank=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='DeepLabV3+', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='GestureControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.FileField(upload_to='gesture_input/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='gesture_output/')),
                ('landmarks', models.JSONField(default=list)),
                ('ai_description', models.TextField(blank=True)),
                ('technical_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='FacialRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_image', models.ImageField(upload_to='facial_input/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='facial_output/')),
                ('recognized', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_description', models.TextField(blank=True)),
                ('technical_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.demosession')),
            ],
        ),
    ]
